### ISSUE TITLE
{ПРИОРИТЕТ=2} Условия при GET в API

### ISSUE THREAD

**Issue by RSamokhin** [RSamokhin/rcg#2]
Глобально на все апи добавить возможность подставлять условия в where - пока что без составных запросов, выборка должна быть возможной по нескольким параметрам с условиями
- *=
- $=
- ^=
- =
- >
- <
- >=
- <=

При неприменимости к конкретному типу данных селектор должен игнорироваться, но при этом в обратную сторону должен работать, т.е.
* > для строк игнорируется
* *= для дат работает также как и для строк

**Comment by PomanoB** [comment]
Условия:
=
>
>=
<
<=
<>
~ - like
Пример:
/news?whereid=1&where=authorId=123
