### ISSUE TITLE
{ПРИОРИТЕТ=3}Написать механизм добавления записей через админку

### ISSUE THREAD

**Issue by RSamokhin** [RSamokhin/rcg#4]
Кнопку добавления строк + без загрузки страницы

**Comment by PomanoB** [comment]
Что имеется ввиду? Ведь есть методы PUT?
28 авг. 2015 г. 19:15 пользователь "Roman" <notifications@github.com>
написал:

**Comment by RSamokhin** [comment]
я про фронтенд - протестили
